version: '2'
services:
  consul:
    image: consul:1.6
    ports:
      - '8300:8300'
      - '8500:8500'
      - '8600:8600'
    volumes:
      - consul-data:/data
      - consul-config:/config
    command: agent -server -data-dir=/data -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect=1 -ui
  postgresql:
    image: postgres:11
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: wazo
      POSTGRES_PASSWORD: wazo
      POSTGRES_DB: wazo

volumes:
  postgres-data:
  consul-data:
  consul-config:
